baseURL: 'https://ahmadnaofficial.github.io/personal-blog/'
title: Ahmed.NADS
paginate: 5
theme: charlolamode



menu:
    main:
        - name: Contact
          url: contact/
          weight: 30
        - name: Articles
          url: articles/
          weight: 20
        # - name: Catagories
        #   url: catagories/
        #   weight: 10


params:
    author: Ahmed Nasser


    defaultTheme: auto
    disableThemeToggle: true
    ShowShareButtons: true
    ShowReadingTime: true
    displayFullLangName: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    ShowToc: true

    profileMode:
        enabled: true
        title: Ahmed Nasser Almotawah
        imageUrl: "/images/profile.jpg"
        imageTitle: Ahmad.NADS
        # imageWidth: 120
        # imageHeight: 120
        # buttons:
            
    mainSections:
      - articles

    socialIcons:
        - name: twitter
          url: "https://twitter.com/AhmedNasser_DS"
        - name: github
          url: "https://github.com/AhmadNAofficial"
        - name: linkedin
          url: "https://www.linkedin.com/in/ahmed-almotawah-9a5828247/"

     
      # - name: youtube
      #   url: yoururl
      # - name: twitter
      #   url: yoururl
      # - name: facebook
      #   url: yoururl


    
    # assets:
    #       favicon: "/images/favicon.ico"
    #       favicon16x16: "/images/favicon-16x16.png"
    #       favicon32x32: "/images/favicon-32x32.png"
    #       apple_touch_icon: "/images/apple-touch-icon.png"
    #       safari_pinned_tab: "/images/apple-touch-icon.png"



enableInlineShortcodes: true
enableRobotsTXT: true
enableEmoji: true
pygmentsUseClasses: true

minify:
    disableXML: true

